baseURL = 'https://docs.slapbirdapm.com'
languageCode = 'en-us'
title = 'SlapbirdAPM Docs'
theme = ['hugo-book']

[menu]
[[menu.before]]
  name = "Getting Started"
  url = "https://docs.slapbirdapm.com"
  weight = 0
[[menu.after]]
  name = "Return to SlapbirdAPM"
  url = "https://slapbirdapm.com"
  weight = 0

[params]
BookSection = '*'
